<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e691a29e-b7ee-4d7b-b33d-dab861455088</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>('//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[3]/div[1]/label[1]/span[2]',)</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>